services:
  cardexporter:
    image: videreproject/mtgosdk:headless
    container_name: cardexporter
    profiles:
      - import
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:99
      - WINEDEBUG=-all
    volumes:
      - .:/workspace
      - carddata-wine-prefix:/home/wine/.wine
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/xvfb-entrypoint.sh"]
    command: ["wine-run", "CardExporter/CardExporter.csproj", "import", "--start-client"]

volumes:
  carddata-wine-prefix:
